version: '3.8'

services:
  app:
    container_name: full-fledged-rest-api
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./
    depends_on:
      - postgresql
    environment:
      - SPRING_PROFILES_ACTIVE=prod # replace with the desired profile
    ports:
      - "8080:8080"
    restart: on-failure

  postgresql:
    image: 'postgres:16.2-alpine'
    container_name: postgresql
    environment:
      - POSTGRES_DB=user_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: on-failure