version: '3'

services:
  app:
    container_name: bvp-task-application
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/user_api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    restart: unless-stopped

  postgresql:
    image: 'postgres:16.2-alpine'
    container_name: postgresql
    environment:
      - POSTGRES_DB=user_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped