server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  application:
    name: BVP-Software-task
  datasource:
    url: jdbc:postgresql://localhost:5432/user_api
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: local@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 182b9e058ec60b5d271a0b77a697c5ace98ced588f6c6cdd13bc303f175274b5
      expiration: 86400000
      refresh-token:
        expiration: 604800000
    confirm-token:
      lifetime: 10

logging:
  level:
    root=WARN:
  file:
    name: bvp-software-task.log
  logback:
    rollingpolicy:
      max-file-size: 10MB