server:
  port: 80

spring:
  config:
    activate:
      on-profile: production
  application:
    name: BVP-Software-task-Prod
  datasource:
    url: jdbc:postgresql://${HOST:dbhost}:5432/user_api_prod
    driver-class-name: org.postgresql.Driver
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.bvp-software.com
    port: 465
    username: prod_username
    password: prod_password
    properties:
      mail:
        smtp:
          auth: true

application:
  security:
    jwt:
      secret-key: 182b9e058ec60b5d271a0b77a697c5ace98ced588f6c6cdd13bc303f175274b5
      expiration: 86400000
      refresh-token:
        expiration: 604800000
    confirm-token:
      lifetime: 10