spring:
  application:
    name: BVP-Software-task
  datasource:
    url: jdbc:postgresql://localhost:5432/user_api
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true