server:
  port: 8081

spring:
  config:
    activate:
      on-profile: qa
  application:
    name: Full-Fledged-Rest-API-QA
  datasource:
    url: jdbc:postgresql://postgresql:5432/user_api
    driver-class-name: org.postgresql.Driver
    username: qa_user
    password: qa_password
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: // ENTER YOUR MAIL ADDRESS
    password: // ENTER YOUR PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 182b9e058ec60b5d271a0b77a697c5ace98ced588f6c6cdd13bc303f175274b5
      expiration: 86400000
      refresh-token:
        expiration: 604800000
    confirm-token:
      lifetime: 10

logging:
  level:
    root=WARN:
  file:
    name: logging.log
  logback:
    rollingpolicy:
      max-file-size: 10MB