server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  application:
    name: BVP-Software-task
  datasource:
    url: jdbc:postgresql://${LOCALHOST:localhost}:5432/user_api
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 465
    username: local_username
    password: local_password
    properties:
      mail:
        smtp:
          auth: true

application:
  security:
    jwt:
      secret-key: 182b9e058ec60b5d271a0b77a697c5ace98ced588f6c6cdd13bc303f175274b5
      expiration: 86400000
      refresh-token:
        expiration: 604800000
    confirm-token:
      lifetime: 10
  admin:
    email: admin@gmail.com
    password: adminadmin123